asdflj/AE2Things

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/client/gui/GuiCraftingTerminal.java
- src/main/java/com/asdflj/ae2thing/client/gui/container/ContainerCraftingTerminal.java
- src/main/java/com/asdflj/ae2thing/common/storage/CellInventory.java
- src/main/java/com/asdflj/ae2thing/common/storage/backpack/AdventureBackpackHandler.java
- src/main/java/com/asdflj/ae2thing/common/storage/backpack/BaseBackpackHandler.java
- src/main/java/com/asdflj/ae2thing/inventory/item/PortableItemInventory.java
- src/main/java/com/asdflj/ae2thing/loader/ChannelLoader.java
- src/main/java/com/asdflj/ae2thing/network/CPacketFluidUpdate.java
- src/main/java/com/asdflj/ae2thing/network/SPacketMEItemInvUpdate.java
- src/main/java/com/asdflj/ae2thing/util/ModAndClassUtil.java
> Backpack terminal add fluid support

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/common/item/ItemPartThaumatoriumInterface.java
- src/main/java/com/asdflj/ae2thing/common/parts/PartThaumatoriumInterface.java
- src/main/java/com/asdflj/ae2thing/common/tile/TileInfusionInterface.java
- src/main/java/com/asdflj/ae2thing/coremod/ClassTransformer.java
- src/main/java/com/asdflj/ae2thing/coremod/hooker/CoreModHooks.java
- src/main/java/com/asdflj/ae2thing/coremod/transform/TileThaumatoriumTransformer.java
- src/main/java/com/asdflj/ae2thing/inventory/IEssentiaContainer.java
- src/main/java/com/asdflj/ae2thing/inventory/ThaumatoriumInventoryAdapter.java
- src/main/java/com/asdflj/ae2thing/loader/ItemAndBlockHolder.java
- src/main/java/com/asdflj/ae2thing/loader/RecipeLoader.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
- src/main/java/com/asdflj/ae2thing/nei/recipes/DefaultExtractorLoader.java
- src/main/java/com/asdflj/ae2thing/util/NameConst.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
add thaumatorium interface
use infusion pattern terminal to encode pattern
> add thaumatorium interface

- src/main/java/com/asdflj/ae2thing/api/WirelessObject.java
- src/main/java/com/asdflj/ae2thing/client/gui/widget/Component.java
- src/main/java/com/asdflj/ae2thing/common/Config.java
Wireless connection terminal defaults to disabling range detection
> Wireless connection terminal defaults to disabling range detection

- src/main/java/com/asdflj/ae2thing/coremod/ClassTransformer.java
- src/main/java/com/asdflj/ae2thing/coremod/hooker/CoreModHooksClient.java
- src/main/java/com/asdflj/ae2thing/coremod/transform/GuiDualInterfaceTransformer.java
- src/main/java/com/asdflj/ae2thing/util/Ae2ReflectClient.java
- src/main/java/com/asdflj/ae2thing/util/NameConst.java
- src/main/java/com/asdflj/ae2thing/util/TheUtil.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
> fix interface display name

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/client/gui/GuiBaseInterfaceWireless.java
- src/main/java/com/asdflj/ae2thing/client/gui/container/ContainerWirelessDualInterfaceTerminal.java
- src/main/java/com/asdflj/ae2thing/network/CPacketTerminalBtns.java
- src/main/java/com/asdflj/ae2thing/network/SPacketMEItemInvUpdate.java
- src/main/java/com/asdflj/ae2thing/util/GTUtil.java
> dual interface terminal add data stick support

- src/main/java/com/asdflj/ae2thing/client/gui/GuiCraftAmount.java
- src/main/java/com/asdflj/ae2thing/coremod/hooker/CoreModHooks.java
- src/main/java/com/asdflj/ae2thing/network/CPacketCraftRequest.java
> add crafting mode

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/client/gui/container/ContainerWirelessDualInterfaceTerminal.java
- src/main/java/com/asdflj/ae2thing/nei/PatternTerminalRecipeTransferHandler.java
- src/main/java/com/asdflj/ae2thing/network/CPacketTransferRecipe.java
- src/main/java/com/asdflj/ae2thing/util/GTUtil.java
fix dual interface terminal when the priority button is enabled, pattern panel filled recipe is incorrectly
update dep
> fix dual interface pattern panel bug

- src/main/java/com/asdflj/ae2thing/client/gui/widget/ItemPanel.java
- src/main/java/com/asdflj/ae2thing/util/GTUtil.java
- src/main/java/com/asdflj/ae2thing/util/ModAndClassUtil.java
> add 270 support

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/client/gui/BaseMEGui.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiMonitor.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiWirelessDualInterfaceTerminal.java
- src/main/java/com/asdflj/ae2thing/client/gui/IWidgetGui.java
- src/main/java/com/asdflj/ae2thing/client/gui/container/ContainerMonitor.java
- src/main/java/com/asdflj/ae2thing/client/gui/widget/ItemPanel.java
- src/main/java/com/asdflj/ae2thing/util/HBMAeAddonUtil.java
- src/main/java/com/asdflj/ae2thing/util/ModAndClassUtil.java
https://github.com/GlodBlock/HBM-AEAddon
> add hbm ae addon fluid support

- src/main/java/com/asdflj/ae2thing/util/NameConst.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
Fix the bug of TF mana fluid with duplicate names 
It will cause the loss of the mana stored currently
> Fix the bug of TF mana fluid with duplicate names 

- src/main/java/com/asdflj/ae2thing/client/gui/IGuiDrawSlot.java
- src/main/java/com/asdflj/ae2thing/network/CPacketCraftRequest.java
fix dual interface render error
> fix infusion terminal order item crash

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/client/gui/container/ContainerCraftingTerminal.java
- src/main/java/com/asdflj/ae2thing/client/gui/container/slot/SlotTicCraftingTerm.java
- src/main/java/com/asdflj/ae2thing/common/Config.java
- src/main/java/com/asdflj/ae2thing/common/storage/CellInventory.java
- src/main/java/com/asdflj/ae2thing/util/Ae2Reflect.java
- src/main/java/com/asdflj/ae2thing/util/ModAndClassUtil.java
- src/main/java/com/asdflj/ae2thing/util/TicUtil.java
add config let backpack terminal can forge tic tool
fix backpack terminal bug
> add config let backpack terminal can forge tic tool

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/inventory/ItemBiggerAppEngInventory.java
fix right click to place items, reopening the backpack terminal will lost items
> fix right click to place items, reopening the backpack terminal will lost items

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/client/gui/GuiCraftingTerminal.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiMonitor.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiWirelessDualInterfaceTerminal.java
- src/main/java/com/asdflj/ae2thing/client/gui/widget/IGuiMonitor.java
- src/main/java/com/asdflj/ae2thing/client/gui/widget/ItemPanel.java
- src/main/java/com/asdflj/ae2thing/client/me/AdvItemRepo.java
- src/main/java/com/asdflj/ae2thing/client/me/IDisplayRepoExtend.java
- src/main/java/com/asdflj/ae2thing/common/Config.java
- src/main/java/com/asdflj/ae2thing/common/storage/ITFluidCellInventory.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinItemRepo.java
support ae2 521 version(Shift to pause terminal view movement)
support ae2fc 1.4.28 version
> backward compatibility

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/api/AE2ThingAPI.java
- src/main/java/com/asdflj/ae2thing/api/IAE2ThingAPI.java
- src/main/java/com/asdflj/ae2thing/api/ICraftingTerminalAdapter.java
- src/main/java/com/asdflj/ae2thing/client/adapter/AECraftingTerminal.java
- src/main/java/com/asdflj/ae2thing/client/adapter/FCCraftingTerminal.java
- src/main/java/com/asdflj/ae2thing/client/adapter/WCTCraftingTerminal.java
- src/main/java/com/asdflj/ae2thing/client/event/CraftTracking.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinGuiOverlayButton.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinGuiUtils.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinIOverlayHandler.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinNEEContainerDrawHandler.java
- src/main/java/com/asdflj/ae2thing/nei/AEItemOverlayState.java
- src/main/java/com/asdflj/ae2thing/network/CPacketCraftRequest.java
- src/main/java/com/asdflj/ae2thing/proxy/ClientProxy.java
- src/main/java/com/asdflj/ae2thing/util/Util.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/mixins.ae2thing.late.json
universal terminal add ctrl+click request missing item support
fix crafting terminal recipe overlay support search me terminal
add crafable icon in recipe overlay
> ae terminal nei support

- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/asdflj/ae2thing/api/AE2ThingAPI.java
- src/main/java/com/asdflj/ae2thing/api/IAE2ThingAPI.java
- src/main/java/com/asdflj/ae2thing/api/Pinned.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinAEBaseGui.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinGuiCraftConfirm.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinGuiOverlayButton.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinItemRepo.java
- src/main/java/com/asdflj/ae2thing/network/CPacketCraftRequest.java
- src/main/java/com/asdflj/ae2thing/network/SPacketMEItemInvUpdate.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/mixins.ae2thing.late.json
fix shift + ctrl + click to request missing item,can't pinned item
> fix shift + ctrl + click to request missing item,can't pinned item

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/api/Pinned.java
- src/main/java/com/asdflj/ae2thing/client/gui/IGuiDrawSlot.java
- src/main/java/com/asdflj/ae2thing/client/gui/container/BaseMonitor/FluidMonitor.java
- src/main/java/com/asdflj/ae2thing/client/render/RenderHelper.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinAEBaseGui.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinContainerCraftConfirm.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/MixinGuiCraftConfirm.java
- src/main/java/com/asdflj/ae2thing/network/SPacketMEItemInvUpdate.java
- src/main/java/com/asdflj/ae2thing/proxy/ClientProxy.java
- src/main/java/com/asdflj/ae2thing/util/TheUtil.java
> Fix pinned ghost item

- src/main/java/com/asdflj/ae2thing/api/Pinned.java
- src/main/java/com/asdflj/ae2thing/client/gui/IGuiDrawSlot.java
- src/main/java/com/asdflj/ae2thing/client/gui/container/ContainerInfusionPatternTerminal.java
- src/main/java/com/asdflj/ae2thing/client/gui/container/slot/InfusionTerminalSlotPatternFake.java
- src/main/java/com/asdflj/ae2thing/client/render/ISlotRender.java
- src/main/java/com/asdflj/ae2thing/client/render/RenderFluidDrop.java
- src/main/java/com/asdflj/ae2thing/client/render/RenderFluidPacketPatternSlot.java
- src/main/java/com/asdflj/ae2thing/client/render/RenderItemPhial.java
- src/main/java/com/asdflj/ae2thing/client/render/SlotRender.java
- src/main/java/com/asdflj/ae2thing/common/item/ItemPhial.java
- src/main/java/com/asdflj/ae2thing/network/SPacketMEItemInvUpdate.java
- src/main/java/com/asdflj/ae2thing/util/TheUtil.java
now infusion pattern terminal will encode as item phial not crafting aspect
> rework infusion pattern terminal

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/client/gui/BaseMEGui.java
- src/main/java/com/asdflj/ae2thing/nei/HistoryOption.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
> nei add draw terminal  history button

- src/main/java/com/asdflj/ae2thing/api/Constants.java
- src/main/java/com/asdflj/ae2thing/api/MouseWheelHandler.java
- src/main/java/com/asdflj/ae2thing/api/adapter/pattern/AEPatternTerminalExTransferHandler.java
- src/main/java/com/asdflj/ae2thing/api/adapter/pattern/AEPatternTerminalTransferHandler.java
- src/main/java/com/asdflj/ae2thing/api/adapter/pattern/FCPatternTerminal.java
- src/main/java/com/asdflj/ae2thing/api/adapter/pattern/IPatternTerminalAdapter.java
- src/main/java/com/asdflj/ae2thing/client/gui/IGuiDrawSlot.java
- src/main/java/com/asdflj/ae2thing/client/gui/container/widget/PatternContainer.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/nee/MixinGuiEventHandler.java
- src/main/java/com/asdflj/ae2thing/loader/BRLoader.java
- src/main/java/com/asdflj/ae2thing/loader/PatternTerminalMouseWheelLoader.java
- src/main/java/com/asdflj/ae2thing/nei/PatternTerminalRecipeTransferHandler.java
- src/main/java/com/asdflj/ae2thing/proxy/ClientProxy.java
- src/main/java/com/asdflj/ae2thing/proxy/CommonProxy.java
- src/main/resources/mixins.ae2thing.late.json
> rework scroll  pattern terminal item

- src/main/java/com/asdflj/ae2thing/client/render/RenderHelper.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/ae/MixinAEBaseGui.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/nei/MixinGuiContainerManager.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/nei/MixinItemHistoryPanel.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
- src/main/java/com/asdflj/ae2thing/nei/PatternTerminalRecipeTransferHandler.java
- src/main/java/com/asdflj/ae2thing/nei/TerminalInventoryStateOption.java
- src/main/java/com/asdflj/ae2thing/proxy/ClientProxy.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
- src/main/resources/mixins.ae2thing.late.json
alt+ mmb to quick fill stack name to search field
> more nei support

- src/main/java/com/asdflj/ae2thing/nei/ButtonConstants.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
- src/main/java/com/asdflj/ae2thing/util/BRUtil.java
- src/main/java/com/asdflj/ae2thing/util/GTUtil.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
> Pattern ignore hatches when encoding

- src/main/java/com/asdflj/ae2thing/client/gui/GuiBaseInterfaceWireless.java
- src/main/java/com/asdflj/ae2thing/loader/PatternTerminalLoader.java
- src/main/java/com/asdflj/ae2thing/loader/PatternTerminalMouseWheelLoader.java
- src/main/java/com/asdflj/ae2thing/nei/BaseToggleButton.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
> fix nei crash

- src/main/java/com/asdflj/ae2thing/api/Pinned.java
- src/main/java/com/asdflj/ae2thing/nei/ButtonConstants.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
> add pin bar option

- src/main/java/com/asdflj/ae2thing/client/gui/GuiCraftingStatus.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/ae/MixinContainerCraftConfirm.java
- src/main/java/com/asdflj/ae2thing/coremod/mixin/ae/MixinGuiCraftConfirm.java
- src/main/java/com/asdflj/ae2thing/network/CPacketTerminalBtns.java
- src/main/java/com/asdflj/ae2thing/util/NameConst.java
- src/main/java/com/asdflj/ae2thing/util/Util.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
> add replan btn

- src/main/java/com/asdflj/ae2thing/api/adapter/item/terminal/FCUltraTerminal.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiPatternValueName.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiTerminalMenu.java
- src/main/java/com/asdflj/ae2thing/nei/BaseToggleButton.java
- src/main/java/com/asdflj/ae2thing/nei/ButtonConstants.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
- src/main/java/com/asdflj/ae2thing/util/NameConst.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
> terminal menu gui

- src/main/java/com/asdflj/ae2thing/api/Constants.java
- src/main/java/com/asdflj/ae2thing/api/adapter/item/terminal/FCUltraTerminal.java
- src/main/java/com/asdflj/ae2thing/api/adapter/item/terminal/IItemTerminal.java
- src/main/java/com/asdflj/ae2thing/api/adapter/item/terminal/TerminalItems.java
- src/main/java/com/asdflj/ae2thing/api/adapter/item/terminal/UltraTerminalHandler.java
- src/main/java/com/asdflj/ae2thing/api/adapter/item/terminal/WCTWirelessCraftingTerminalHandler.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiTerminalMenu.java
- src/main/java/com/asdflj/ae2thing/util/BaublesUtil.java
fix terminal menu can't open terminal in baubles slot
> fix terminal menu can't work in server

- src/main/java/com/asdflj/ae2thing/common/storage/backpack/AdventureBackpackHandler.java
fix backpack terminal use AdventureBackpack to store item inv size incorrect
> fix backpack terminal bug

- src/main/java/com/asdflj/ae2thing/api/Constants.java
- src/main/java/com/asdflj/ae2thing/api/InventoryActionExtend.java
- src/main/java/com/asdflj/ae2thing/client/gui/widget/PatternPanel.java
- src/main/java/com/asdflj/ae2thing/crossmod/waila/CellContentHandlerWaila.java
- src/main/java/com/asdflj/ae2thing/crossmod/waila/CraftingStatePreviewWaila.java
- src/main/java/com/asdflj/ae2thing/crossmod/waila/WailaInit.java
- src/main/java/com/asdflj/ae2thing/nei/ButtonConstants.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
- src/main/java/com/asdflj/ae2thing/network/CPacketInventoryActionExtend.java
- src/main/java/com/asdflj/ae2thing/network/SPacketCraftingStateUpdate.java
- src/main/java/com/asdflj/ae2thing/util/CPUCraftingPreview.java
- src/main/java/com/asdflj/ae2thing/util/InventoryActionExtend.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
> Cpu crafting preview

- dependencies.gradle
- src/main/java/com/asdflj/ae2thing/client/gui/GuiBaseInterfaceWireless.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiMonitor.java
- src/main/java/com/asdflj/ae2thing/client/gui/GuiWirelessConnectorTerminal.java
- src/main/java/com/asdflj/ae2thing/client/gui/widget/ItemPanel.java
- src/main/java/com/asdflj/ae2thing/client/gui/widget/THGuiTextField.java
- src/main/java/com/asdflj/ae2thing/nei/ButtonConstants.java
- src/main/java/com/asdflj/ae2thing/nei/NEI_TH_Config.java
- src/main/java/com/asdflj/ae2thing/nei/PatternTerminalRecipeTransferHandler.java
- src/main/java/com/asdflj/ae2thing/util/GTUtil.java
- src/main/java/com/asdflj/ae2thing/util/NeCharUtil.java
- src/main/resources/assets/ae2thing/lang/en_US.lang
- src/main/resources/assets/ae2thing/lang/zh_CN.lang
> dual interface terminal add autofill recipe name to search filed

- src/main/java/com/asdflj/ae2thing/api/InventoryActionExtend.java
- src/main/java/com/asdflj/ae2thing/api/WirelessObject.java
- src/main/java/com/asdflj/ae2thing/inventory/item/WirelessTerminal.java
- src/main/java/com/asdflj/ae2thing/loader/KeybindLoader.java
- src/main/java/com/asdflj/ae2thing/network/CPacketInventoryActionExtend.java
- src/main/java/com/asdflj/ae2thing/proxy/ClientProxy.java
- src/main/java/com/asdflj/ae2thing/util/BlockPos.java
> add middle click to quick take item stack from me system
